### ISSUE TITLE
Possible to auto inject the necessary html?

### ISSUE THREAD

**Issue by mperkh** [Creatiwity/gatsby-plugin-favicon#1]
Hi - absolutely great plugin thanks a lot!

According to https://github.com/jantimon/favicons-webpack-plugin, it's possible to let webpack also auto inject the necessary html for the generated favicons, if `html-webpack-plugin` is used.

Is that possible? If yes, we could add this to the instructions.

**Comment by julien1619** [comment]
Hi! Thank you very much for your feedback.

I remember that I quickly checked this point and there was an issue because `favicons-webpack-plugin` was generating a lot of things including a manifest for a progressive web app. That manifest was handled by Gatsby and it caused a conflict when I tried to auto inject the necessary html.

Maybe a setting exists to make it working, so, if you want to check that point again, I would be very pleased to merge your PR :)
