### ISSUE TITLE
Compatibility with Gatsby Manifest Plugin

### ISSUE THREAD

**Issue by janschloss** [Creatiwity/gatsby-plugin-favicon#20]
This plugin creates another manifest file.

https://www.gatsbyjs.org/packages/gatsby-plugin-manifest/

Are there plans to create some synergy between your plugin and this one?

**Comment by moonmeister** [comment]
@janschloss I asked basically the same thing here: https://github.com/Creatiwity/gatsby-plugin-favicon/issues/18 ( I didn't get a response). At a basic level they're designed to help with the same issue. This one has implimented the image automation and the gatsby-plugin-manifest has implimentd the customization. 

Since the owners of this repo have been unresponsive I plan to merge the two plugins and send the pr over to the gatsby repo to update the manifest plugin. @KyleAMathews was supportive of this plan, I just need to make it happen. If you want to help, we can make it happen together!

Hope this was helpful!

**Comment by aziz-ka** [comment]
I was having the same issue. Here's my workaround. Seems like all you have to do is to set `android: false` in the config file. All this flag does is enables/disables `manifest.json` which is what causes the conflict with [gatsby-plugin-manifest](https://www.gatsbyjs.org/packages/gatsby-plugin-manifest) in the first place
https://github.com/Creatiwity/gatsby-plugin-favicon/blob/5a3ee5bd09f00ebe534df663d357c8308dcc4d6a/src/gatsby-ssr.js#L24

**Comment by moonmeister** [comment]
@janschloss @aziz-ka Thanks for the workaround info. FYI the gatsby-plugin-manifest has been updated with auto icon generation/resize support for manifest. Using your workarround you can generate images for other browsers.  Check it out here: https://github.com/gatsbyjs/gatsby/pull/4382

**Comment by PolGuixe** [comment]
@moonmeister thanks for the clarifications

I still don't understand the workaround fully. 

If I install and configure `gatsby-plugin-manifest` I get the manifest but I don't get a favicon. 
In order to get the favicons I have to install and configure `gatsby-plugin-favicons`. 

Is that the current state?

**Comment by moonmeister** [comment]
The Gatsby-plugin-manifest can now autogenerate images. But it only does so
for the web app manifest spec (what gatsby-plugin-favicon calls android,
but is now used more widely). If you want the favicon generated you will
need. The favicon plug-in, you'll just need to disable android.

AJ

On Jun 10, 2018 9:01 AM, "PolGuixe" <notifications@github.com> wrote:

@moonmeister <https://github.com/moonmeister> thanks for the clarifications

I still don't understand the workaround fully.

If I install and configure gatsby-plugin-manifest I get the manifest but I
don't get a favicon.
In order to get the favicons I have to install and configure
gatsby-plugin-favicons.

Is that the current state?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Creatiwity/gatsby-plugin-favicon/issues/20#issuecomment-396060267>,
or mute the thread

**Comment by madeleineostoja** [comment]
Ah, only just saw this - made an issue re: that last comment here: https://github.com/gatsbyjs/gatsby/issues/5887

**Comment by julien1619** [comment]
Thank you for the feedback! It's been a long time but the version 3.1.0 is just out right now and supports a full manifest configuration with Gatsby v2.
